name: Node.js CI

on:
  push:
    branches:
      - main  # Change to your default branch

jobs:
  build:

    runs-on: self-hosted  # Use your self-hosted runner here

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Change to the version of Node.js you're using

    - name: Install dependencies
      run: npm install

    - name: Build and start application
      run: npm start
